version: '3.8'

services:
 postgres:
  image: postgres:17
  container_name: employee_db
  restart: always
  environment: 
    POSTGRES_DB: employee_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: SiddharthPostgres@123

  ports:
   - "5432:5432"

  volumes:
   - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

